version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: celery -A app.tasks worker --loglevel=info --concurrency=1